const state={intent:'newpm',role:'New PM',step:0,method:'Hybrid',risk:'Vendor dependency',complexity:'Multi-team',project:'Mobile banking platform integration'};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
window.addEventListener('DOMContentLoaded',()=>{bootIntro();renderIntents();renderStepper();wireWizard();renderNav();});
function bootIntro(){const lines=['Track delivery.','Trace causes.','Learn patterns.','Understanding your delivery environment...'];let i=0;const el=$('#introLine');const t=setInterval(()=>{i++; if(i<lines.length)el.textContent=lines[i]; else{clearInterval(t);setTimeout(()=>{$('#intro').classList.remove('open');$('#entry').classList.remove('hidden')},400)}},550)}
function renderIntents(){const grid=$('#intentGrid');grid.innerHTML=intents.map(x=>`<article class="intent-card" onclick="selectIntent('${x.id}')"><i class="${x.icon}"></i><h3>${x.title}</h3><p>${x.desc}</p><small>${x.role}</small></article>`).join('')}
function selectIntent(id){const item=intents.find(x=>x.id===id)||intents[0];state.intent=id;state.role=item.role;$('#roleName').textContent=item.role;$('#entry').classList.add('hidden');$('#setup').classList.remove('hidden')}
function renderStepper(){const s=$('#stepper');s.innerHTML=[0,1,2,3].map(i=>`<span class="${i<=state.step?'active':''}"></span>`).join('')}
function wireWizard(){
 $$('.chips button').forEach(b=>b.onclick=()=>{$('#projectName').value=b.dataset.project});
 $$('.choice-grid').forEach(g=>g.addEventListener('click',e=>{const c=e.target.closest('.choice');if(!c)return;g.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');state[g.dataset.field]=c.dataset.value;}));
 $('#backBtn').onclick=()=>{if(state.step>0){state.step--;showStep()}else{$('#setup').classList.add('hidden');$('#entry').classList.remove('hidden')}};
 $('#nextBtn').onclick=()=>{state.project=$('#projectName').value.trim()||'New delivery initiative'; if(state.step<3){state.step++;showStep()}else generateWorkspace()};
}
function showStep(){$$('.step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===state.step));renderStepper();$('#nextBtn').textContent=state.step===3?'Generate Workspace':'Continue'}
function generateWorkspace(){$('#setup').classList.add('hidden');$('#generate').classList.remove('hidden');const items=$$('#genList li');items.forEach((li,i)=>setTimeout(()=>li.classList.add('done'),550*(i+1)));setTimeout(()=>{renderWorkspace();$('#generate').classList.add('hidden');$('#app').classList.remove('hidden')},3600)}
function renderNav(){const nav=$('#nav');nav.innerHTML=navGroups.map(g=>`<div class="nav-group"><div class="nav-label">${g.label}</div>${g.items.map(([id,label])=>`<a class="nav-item ${id==='dashboard'?'active':''}" data-sec="${id}" onclick="showSection('${id}')"><i class="ti ti-circle-dot"></i>${label}</a>`).join('')}</div>`).join('')}
function showSection(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));$$('.nav-item').forEach(a=>a.classList.toggle('active',a.dataset.sec===id));window.scrollTo({top:0,behavior:'smooth'})}
function restart(){location.reload()}
function renderWorkspace(){
 $('#workspaceTitle').textContent=state.project;$('#workspaceSub').textContent=`${state.role} · ${state.method} · ${state.complexity}`;
 renderDashboard();renderSetupOutput();renderDelivery();renderRaid();renderGovernance();renderPeople();renderImpact();renderLearning();renderReports();renderIntegrations();
}
function riskNarrative(){return `This ${state.method.toLowerCase()} initiative has elevated ${state.risk.toLowerCase()} risk due to ${state.complexity.toLowerCase()} coordination. VeloClear generated starter controls, review cadence and escalation thresholds to reduce delivery ambiguity from day one.`}
function renderDashboard(){
 $('#dashboard').innerHTML=`<div class="hero-panel"><div><p class="eyebrow">Generated delivery narrative</p><h1>Your workspace is ready.</h1><p class="narrative">${riskNarrative()}</p></div><div class="card"><span class="tag green">Ready</span><h3>Setup intelligence</h3><p>Generated from project type, method, risk profile and complexity.</p></div></div><div class="kpi-row"><div class="kpi"><b>5</b><span>phases generated</span></div><div class="kpi amber"><b>4</b><span>starter risks</span></div><div class="kpi green"><b>6</b><span>stakeholders mapped</span></div><div class="kpi red"><b>1</b><span>critical dependency</span></div></div><div class="grid-2"><div class="card"><h3>Delivery health narrative</h3><p>Primary concern: ${state.risk}. Recommended first action: validate ownership, date and trigger condition before the first steering checkpoint.</p></div><div class="card"><h3>Next best actions</h3><div class="raid-list"><div class="raid-item"><b>Confirm sponsor and decision rights</b><span>Governance clarity reduces escalation drag.</span></div><div class="raid-item"><b>Review generated RAID</b><span>Turn starter assumptions into owned actions.</span></div><div class="raid-item"><b>Import existing plan</b><span>Connect Jira, ADO, MSP or upload Excel.</span></div></div></div></div>`
}
function renderSetupOutput(){
 $('#setup-output').innerHTML=`<div class="hero-panel"><div><p class="eyebrow">Project Setup Intelligence</p><h1>${state.project}</h1><p class="narrative">Generated structure for a ${state.complexity.toLowerCase()} ${state.method.toLowerCase()} initiative with likely ${state.risk.toLowerCase()} exposure.</p></div><div class="card"><h3>Recommended cadence</h3><p>Weekly RAID review · fortnightly steering · monthly portfolio health check.</p></div></div><div class="grid-3"><div class="card"><h3>Starter delivery model</h3><p>Discovery → Build → Integration → UAT → Rollout → Hypercare.</p></div><div class="card"><h3>Governance model</h3><p>Decision thresholds, RAG commentary, CR control and escalation stages created.</p></div><div class="card"><h3>Learning model</h3><p>Lessons and delivery signals will be captured into cross-project memory.</p></div></div>`
}
function renderDelivery(){
 $('#delivery').innerHTML=`<p class="eyebrow">Delivery</p><h1 class="screen-title">Timeline & dependencies</h1><div class="card"><h3>Generated phase timeline</h3><div class="timeline"><div class="phase">Discovery</div><div class="phase">Build</div><div class="phase">Integration</div><div class="phase">UAT</div><div class="phase">Rollout</div><div class="phase">Hypercare</div></div></div><div class="grid-2" style="margin-top:14px"><div class="card"><h3>Critical dependency</h3><p>External integration milestone must be confirmed before UAT entry.</p><span class="tag red">Trigger required</span></div><div class="card"><h3>Sprint rhythm</h3><p>2-week sprint cadence with governance checkpoint every second sprint.</p><span class="tag">Hybrid</span></div></div>`
}
function renderRaid(){
 const risks=['External vendor misses integration milestone','Business approvals delay UAT sign-off','Scope expansion affects sprint capacity','Compliance evidence incomplete before release'];
 $('#raid').innerHTML=`<p class="eyebrow">RAID</p><h1>Generated starter RAID</h1><div class="raid-list">${risks.map((r,i)=>`<div class="raid-item"><b>R00${i+1} · ${r}</b><span>Trigger: observable event required · Owner: to assign · Response: mitigate</span></div>`).join('')}</div>`
}
function renderGovernance(){
 $('#governance').innerHTML=`<p class="eyebrow">Governance</p><h1>RAG · Change · Escalation · Decisions</h1><div class="grid-2"><div class="card"><h3>RAG rules</h3><p>Green: one-line confidence. Amber: issue + recovery plan. Red: root cause + decision needed.</p></div><div class="card"><h3>Escalation threshold</h3><p>Any blocker open beyond 48 hours without owner or recovery path escalates automatically.</p></div><div class="card"><h3>Change control</h3><p>Assess all CRs against scope, schedule, cost and quality before approval.</p></div><div class="card"><h3>Decision rights</h3><p>PM, sponsor and steering thresholds created for delivery decisions.</p></div></div>`
}
function renderPeople(){
 $('#people').innerHTML=`<p class="eyebrow">People</p><h1>Stakeholder model</h1><div class="grid-3"><div class="card"><h3>Executive Sponsor</h3><p>High power · medium interest · decision owner</p></div><div class="card"><h3>Business Owner</h3><p>High interest · requirements and acceptance</p></div><div class="card"><h3>Vendor Lead</h3><p>Critical dependency owner</p></div><div class="card"><h3>Delivery Team</h3><p>Build and sprint execution</p></div><div class="card"><h3>PMO</h3><p>Governance and reporting assurance</p></div><div class="card"><h3>Compliance</h3><p>Controls and release evidence</p></div></div>`
}
function renderImpact(){
 $('#impact').innerHTML=`<p class="eyebrow">Signature Intelligence</p><h1>Impact Trace</h1><p class="narrative">A causal chain that connects risk, issue, escalation, decision and learning.</p><div class="trace"><div class="trace-step"><span class="tag red">Risk Trigger</span><h3>Vendor milestone missed</h3><p>Integration API delivery slips beyond agreed sprint checkpoint.</p></div><div class="trace-step"><span class="tag amber">Issue Created</span><h3>UAT entry threatened</h3><p>System creates issue and updates schedule RAG to amber.</p></div><div class="trace-step"><span class="tag">Decision Needed</span><h3>Fallback plan required</h3><p>Sponsor to approve internal workaround or vendor escalation route.</p></div><div class="trace-step"><span class="tag green">Learning Captured</span><h3>Future project rule</h3><p>Vendor integrations require fallback plan before build exit.</p></div></div>`
}
function renderLearning(){
 $('#learning').innerHTML=`<p class="eyebrow">Learning Engine</p><h1>Cross-project learning</h1><div class="grid-2"><div class="card"><h3>Recurring pattern</h3><p>Vendor dependencies commonly create late UAT pressure when trigger dates are undefined.</p></div><div class="card"><h3>PM coaching prompt</h3><p>Convert vague risks into observable trigger events before governance review.</p></div><div class="card"><h3>Portfolio signal</h3><p>Projects with multi-team complexity should identify dependency owner by phase 2.</p></div><div class="card"><h3>Reusable lesson</h3><p>Escalation works better when decision options are prepared before steering.</p></div></div>`
}
function renderReports(){
 $('#reports').innerHTML=`<p class="eyebrow">Reports</p><h1>Executive narratives</h1><div class="hero-panel"><div><h1>Portfolio-ready summary</h1><p class="narrative">${state.project} is structurally ready for initiation. Primary risk is ${state.risk.toLowerCase()}. Recommended governance action: validate dependency ownership and escalation thresholds before build starts.</p></div><div class="card"><span class="tag green">Generated</span><h3>Steering pack</h3><p>RAG, RAID, timeline, decisions and narrative summary.</p></div></div>`
}
function renderIntegrations(){
 $('#integrations').innerHTML=`<p class="eyebrow">Import / Connect</p><h1>Bring existing projects into VeloClear</h1><div class="upload-zone"><i class="ti ti-cloud-upload"></i><h3>Upload existing project files</h3><p>Excel, CSV, MS Project exports, RAID logs or steering packs. VeloClear extracts risks, milestones, stakeholders and decisions.</p><button class="btn primary"><i class="ti ti-upload"></i> Choose files</button></div><div class="connect-grid"><div class="connector"><i class="ti ti-brand-jira"></i><h3>Jira</h3><p>Issues, epics, sprint signals.</p></div><div class="connector"><i class="ti ti-brand-azure"></i><h3>Azure DevOps</h3><p>Work items and delivery flow.</p></div><div class="connector"><i class="ti ti-file-spreadsheet"></i><h3>Excel / CSV</h3><p>RAID, plans and reports.</p></div><div class="connector"><i class="ti ti-calendar-stats"></i><h3>MS Project</h3><p>Milestones and baselines.</p></div><div class="connector"><i class="ti ti-brand-slack"></i><h3>Slack</h3><p>Blockers and delivery updates.</p></div><div class="connector"><i class="ti ti-brand-teams"></i><h3>Teams</h3><p>Meeting decisions and actions.</p></div><div class="connector"><i class="ti ti-table"></i><h3>Smartsheet</h3><p>Portfolio registers.</p></div><div class="connector"><i class="ti ti-plug-connected"></i><h3>ServiceNow</h3><p>Incidents and change signals.</p></div></div>`
}
