function esc(s){ return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function button(text, icon, onClick, type='ghost'){ return `<button class="btn btn-${type} btn-sm" onclick="${onClick}"><i class="ti ${icon}"></i>${text}</button>`; }
function topbar(title, sub, actions=[]){ return `<div class="topbar"><div><div class="topbar-title">${title}</div><div class="topbar-sub">${sub}</div></div><div class="topbar-actions">${actions.join('')}</div></div>`; }
function badge(type, text){ return `<span class="badge badge-${type}">${text}</span>`; }
function dot(type){ return `<span class="dot ${type}"></span>`; }
function field(label, type, value){ return `<div class="field"><label>${label}</label><${type==='select'?'select':'input'} ${type==='select'?'':`value="${esc(value)}"`}>${type==='select'?`<option>${esc(value)}</option><option>Enterprise transformation</option><option>Product launch</option><option>Regulatory project</option>`:''}</${type==='select'?'select':'input'}></div>`; }
function flowStep(num,title,copy){ return `<div class="flow-step"><div class="flow-dot">${num}</div><div><div class="flow-title">${title}</div><div class="flow-copy">${copy}</div></div></div>`; }
function setupMini(title, body){ return `<div class="card lift card-p"><div class="card-title">${title}</div><div class="card-sub" style="font-size:12px;line-height:1.6;margin-top:8px">${body}</div></div>`; }

function renderDashboard(){
  const role = roles.find(r=>r.id===currentRole) || roles[3];
  document.getElementById('s-dashboard').innerHTML = topbar('Portfolio Command Centre', `${role.title} view · live demo data · role-aware workspace`, [button('Reports','ti-report','go(\'reports\')'), button('New Project','ti-plus','go(\'setup\')','primary')]) + `
    <div class="content">
      <div class="hero-panel" style="margin-bottom:14px">
        <div>
          <span class="hero-kicker"><i class="ti ti-pulse"></i> Delivery Health Narrative</span>
          <h1 class="hero-title">Track every project. <em>Trace every delay.</em> <strong>Learn from everything.</strong></h1>
          <p class="hero-copy">Portfolio health is amber. The primary driver is a shared vendor dependency affecting Apex integration and Meridian testing. Recommended action: confirm fallback ownership before the next steering review.</p>
          <div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:16px">
            <button class="btn btn-primary" onclick="go('intelligence')"><i class="ti ti-route"></i> Open Impact Trace</button>
            <button class="btn btn-ghost" onclick="showNarrative()"><i class="ti ti-file-text"></i> View executive summary</button>
          </div>
        </div>
        <div class="mock-phone"><div class="mock-screen">
          <div class="card-title">Today’s signal</div><div class="card-sub">Generated from RAID, timeline and RAG</div>
          <div class="flow-card" style="padding:12px 0 0">
            ${flowStep(1,'Risk trigger fired','Vendor missed sprint 3 API milestone.')}
            ${flowStep(2,'Issue created','I001 linked to Apex integration delay.')}
            ${flowStep(3,'Learning suggested','Require fallback plan before Phase 3.')}
          </div>
        </div></div>
      </div>
      <div class="g4" style="margin-bottom:14px">${kpis()}</div>
      <div class="card card-p" style="margin-bottom:14px">${healthBar()}</div>
      <div class="g-3-2" style="margin-bottom:14px">
        <div class="card"><div class="card-header"><div><div class="card-title">Portfolio RAG Summary</div><div class="card-sub">Click a row to open project workspace</div></div><a class="card-link" onclick="go('project')">Project workspace →</a></div>${ragTable()}</div>
        <div class="card"><div class="card-header"><div><div class="card-title">EVM Performance</div><div class="card-sub">CPI & SPI per project</div></div><a class="card-link" onclick="go('delivery')">Delivery →</a></div><div class="card-p">${evmBars()}</div></div>
      </div>
      <div class="g-3-2">
        <div class="card"><div class="card-header"><div><div class="card-title">Risk Heat Map</div><div class="card-sub">Probability vs impact · hover cells</div></div><a class="card-link" onclick="go('delivery')">RAID →</a></div><div class="card-p">${heatMap()}</div></div>
        <div class="narrative-card"><div class="narrative-icon"><i class="ti ti-brain"></i></div><div><h3>Cross-project learning</h3><p><strong>Vendor integration risk</strong> has appeared in 4 previous projects. VeloClear recommends assigning fallback ownership before sprint 2 ends.</p></div></div>
      </div>
    </div>`;
}
function kpis(){ return [
  ['ti-folders','3','ACTIVE PROJECTS','2 closed this quarter',''],['ti-shield-x','3','HIGH RISKS','1 trigger fired','red'],['ti-chart-bar','1.02','PORTFOLIO CPI','cost stable','green'],['ti-clipboard-list','2','PENDING CRS','1 past 48h','amber']
].map(k=>`<div class="card kpi lift ${k[4]}"><div class="kpi-top"><div class="kpi-ico"><i class="ti ${k[0]}"></i></div>${badge(k[4]||'indigo', k[3])}</div><div class="kpi-num">${k[1]}</div><div class="kpi-label">${k[2]}</div><div class="kpi-note">${k[3]}</div></div>`).join(''); }
function healthBar(){ return `<div style="display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:10px"><div><div class="card-title">Portfolio Health</div><div class="card-sub">${dot('green')} 1 Green &nbsp; ${dot('amber')} 1 Amber &nbsp; ${dot('red')} 1 Red &nbsp; ${dot('slate')} 1 Closed</div></div>${badge('amber','Amber trend')}</div><div class="health-track"><span class="health-green" style="flex:1"></span><span class="health-amber" style="flex:1"></span><span class="health-red" style="flex:1"></span><span class="health-closed" style="flex:1"></span></div>`; }
function ragTable(){ return `<table class="tbl"><thead><tr><th>Project</th><th>RAG</th><th>Status</th><th>Sprint</th><th>CPI</th><th>SPI</th></tr></thead><tbody>${projects.map(p=>`<tr onclick="go('project')" style="cursor:pointer"><td><strong>${p.name}</strong><div class="card-sub">${p.owner}</div></td><td>${dot(p.rag)}</td><td>${p.status}</td><td>${p.sprint}</td><td>${p.cpi}</td><td>${p.spi}</td></tr>`).join('')}</tbody></table>`; }
function evmBars(){ return projects.slice(0,3).map(p=> ['CPI','SPI'].map(metric=>{ const v = metric==='CPI'?p.cpi:p.spi; const cls = v>=1?'':v>=.85?'amber':'red'; return `<div class="progress-line"><div class="progress-name">${p.name}</div><div class="progress-label">${metric}</div><div class="progress-bar"><div class="progress-fill ${cls}" style="width:${Math.min(v*90,100)}%"></div></div><div class="progress-val">${v}</div></div>`; }).join('')).join(''); }
function heatMap(){ let html='<div class="heat-grid"><div></div>'; for(let i=1;i<=5;i++) html+=`<div class="heat-head">${i}</div>`; for(let p=5;p>=1;p--){ html+=`<div class="heat-axis">${p}</div>`; for(let i=1;i<=5;i++){ const s=p*i; const cls=s>=15?'heat-x':s>=10?'heat-hi':s>=5?'heat-med':'heat-low'; html+=`<div class="heat-cell ${cls} ${s===15?'risk':''}" onclick="showModal('Risk cell ${s}','Probability ${p} × Impact ${i}', 'This zone contains risks scored ${s}.')">${s}</div>`; } } return html+'</div>'; }

function renderProject(){ document.getElementById('s-project').innerHTML = topbar('Project Workspace','Apex Mobile Platform · role-aware operational hub',[button('Edit project','ti-pencil','showModal(\'Project details\',\'Update metadata and governance settings.\',\'Demo edit panel.\')'),button('Add risk','ti-plus','go(\'delivery\')','primary')]) + `
  <div class="content"><div class="story-card card" style="margin-bottom:14px"><div class="story-left"><span class="eyebrow"><i class="ti ti-briefcase"></i> Live project demo</span><h2>Apex Mobile is <em>moving</em>, but vendor dependency is active.</h2><p>VeloClear connects delivery status, risk, stakeholders, decisions and lessons in one project workspace.</p><div class="story-list"><div>${dot('amber')} Schedule amber due to API handoff</div><div>${dot('green')} Budget and scope stable</div><div>${dot('red')} 1 issue past 48h threshold</div></div></div><div class="card card-p">${healthBar()}<div style="margin-top:14px">${evmBars().split('</div>').slice(0,4).join('</div>')}</div></div></div><div class="feature-grid">${features.slice(0,9).map(featureCard).join('')}</div></div>`; }
function featureCard(f){ const type = f.group==='Governance'?'amber':f.group==='Intelligence'?'indigo':f.group==='People'?'green':'indigo'; return `<div class="card feature-card lift"><div class="feature-icon"><i class="ti ${f.icon}"></i></div><h3>${f.title}</h3><p>${f.desc}</p><div class="mini">${f.tags.map(t=>badge(type,t)).join('')}</div></div>`; }
function renderDelivery(){ const deliveryFeatures = features.filter(f=>f.group==='Delivery'); document.getElementById('s-delivery').innerHTML = topbar('Delivery Operations','Programme timeline · RAID · Sprint workspace · Dependencies',[button('Add RAID','ti-plus','showRaidModal()','primary')]) + `<div class="content"><div class="screen-head"><div><div class="eyebrow"><i class="ti ti-timeline"></i> Delivery flow</div><h1 class="page-title">Risks, dependencies and sprint health in one flow.</h1><p class="page-desc">All delivery features remain available, but they are grouped into the operational flow a PM actually follows.</p></div></div><div class="g-3-2" style="margin-bottom:14px"><div class="card"><div class="card-header"><div><div class="card-title">Programme Timeline</div><div class="card-sub">Click sprint blocks to open sprint intelligence drawer</div></div></div><div class="card-p">${timeline()}</div></div><div class="card"><div class="card-header"><div><div class="card-title">RAID live preview</div><div class="card-sub">Trigger-based risk management</div></div></div><div class="card-p">${raidPreview()}</div></div></div><div class="feature-grid">${deliveryFeatures.map(featureCard).join('')}${featureCard({group:'Delivery',icon:'ti-plug-connected',title:'Dependencies',desc:'Cross-team and external dependencies with owners, due dates and blocker logic.',tags:['External','Blocked','Owner']})}</div></div>`; }
function timeline(){ return `<div class="timeline">${projects.slice(0,3).map((p,idx)=>`<div class="timeline-row"><div class="timeline-name">${p.name}</div>${Array.from({length:8}).map((_,i)=>{ const arr=[['green','green','amber','red','slate','slate','slate','slate'],['green','green','green','green','green','slate','slate','slate'],['green','amber','red','slate','slate','slate','slate','slate']][idx]; return `<div class="sprint-block sprint-${arr[i]}" onclick="openDrawer('${p.name}','Sprint ${i+1}','${arr[i]}')">S${i+1}</div>`; }).join('')}</div>`).join('')}</div>`; }
function raidPreview(){ return `<div class="tab-bar"><button class="tab active">Risks</button><button class="tab">Assumptions</button><button class="tab">Issues</button><button class="tab">Dependencies</button></div><div class="flow-card" style="padding:0">${flowStep('R','Vendor API Delay','Score 15 · Critical · Trigger fired')}${flowStep('A','Branch availability','Validate by 24 May · owner Ops')}${flowStep('I','Integration testing blocked','51 hours open · Stage 2 escalation')}${flowStep('D','Compliance sign-off','Required before sprint 5 close')}</div>`; }
function showRaidModal(){ showModal('Add RAID item','Guided risk capture with coaching prompt.', `<div class="form-grid"><div class="field"><label>Type</label><select><option>Risk</option><option>Assumption</option><option>Issue</option><option>Dependency</option></select></div><div class="field"><label>Owner</label><input placeholder="Owner name"></div><div class="field" style="grid-column:1/-1"><label>Description</label><textarea placeholder="What might happen?"></textarea></div><div class="field" style="grid-column:1/-1"><label>Trigger</label><textarea placeholder="What measurable event proves this risk has happened?"></textarea></div></div>`); }
function renderGovernance(){ document.getElementById('s-governance').innerHTML = topbar('Governance','RAG · Change Control · Escalations · Decisions · Audit',[button('Raise CR','ti-git-pull-request','showModal(\'Raise change request\',\'Integrated change control demo.\',\'Scope, schedule, cost and quality impact are captured together.\')','primary')]) + `<div class="content"><div class="narrative-card" style="margin-bottom:14px"><div class="narrative-icon"><i class="ti ti-shield-check"></i></div><div><h3>Governance without spreadsheet theatre.</h3><p>RAG, change requests, escalations, decision rights, audit trail, reports and import/export remain available — grouped into a clearer governance flow.</p></div></div><div class="feature-grid">${features.filter(f=>f.group==='Governance').map(featureCard).join('')}${featureCard({group:'Governance',icon:'ti-urgent',title:'Escalation Tracker',desc:'4-stage escalation protocol with automatic ageing and sponsor prompts.',tags:['Stage 1','Stage 2','Sponsor']})}${featureCard({group:'Governance',icon:'ti-file-search',title:'Audit Trail',desc:'Immutable record of changes, escalations, decisions and report exports.',tags:['Audit','Export','Evidence']})}${featureCard({group:'Governance',icon:'ti-download',title:'Import / Export',desc:'Templates, CSV/JSON backup and module-level export for low lock-in.',tags:['CSV','JSON','Backup']})}</div></div>`; }
function renderPeople(){ document.getElementById('s-people').innerHTML = topbar('People System','Stakeholders · Engagement · RACI · Comms · Capacity',[button('Add stakeholder','ti-user-plus','showModal(\'Add stakeholder\',\'Power, interest and engagement target.\',\'Stakeholder demo form.\')','primary')]) + `<div class="content"><div class="g-3-2" style="margin-bottom:14px"><div class="story-card card"><div class="story-left"><span class="eyebrow"><i class="ti ti-users"></i> People intelligence</span><h2>Reduce delivery noise by making ownership visible.</h2><p>Stakeholder, RACI, engagement, communications and capacity features stay intact, but the primary interface shows what action is needed.</p></div><div class="flow-card">${flowStep(1,'Sponsor','High power · high interest · manage closely')}${flowStep(2,'Branch managers','Low power · high interest · move resistant → neutral')}${flowStep(3,'QA lead','Capacity risk · sprint 4 conflict')}</div></div><div class="card"><div class="card-header"><div><div class="card-title">Power-interest preview</div><div class="card-sub">Live positioning</div></div></div><div class="card-p"><div style="height:260px;border:1px solid var(--border);border-radius:12px;background:linear-gradient(90deg,transparent 49%,var(--border) 50%,transparent 51%),linear-gradient(transparent 49%,var(--border) 50%,transparent 51%),var(--surface);position:relative"><span class="badge badge-red" style="position:absolute;right:30px;top:34px">Sponsor</span><span class="badge badge-amber" style="position:absolute;left:44px;top:54px">Compliance</span><span class="badge badge-green" style="position:absolute;right:48px;bottom:48px">Branch Ops</span><span class="badge badge-slate" style="position:absolute;left:36px;bottom:42px">Monitor</span></div></div></div></div><div class="feature-grid">${features.filter(f=>f.group==='People').map(featureCard).join('')}${featureCard({group:'People',icon:'ti-message-circle',title:'Comms Plan',desc:'Who gets what update, when, through which channel and by whom.',tags:['Cadence','Channel','Owner']})}</div></div>`; }
function renderIntelligence(){ document.getElementById('s-intelligence').innerHTML = topbar('Delivery Intelligence','Impact Trace · Learning Engine · Cross-project Insights · Health Narrative',[button('Capture lesson','ti-bulb','showModal(\'Capture learning\',\'Reusable delivery lesson.\',\'Lesson linked to trace DT001.\')','primary')]) + `<div class="content"><div class="g-3-2"><div class="card"><div class="card-header"><div><div class="card-title">Impact Trace — DT001</div><div class="card-sub">Blocker → risk → issue → decision → learning</div></div></div><div class="card-p"><div class="trace">${traceSteps.map(t=>`<div class="trace-step ${t[0]}"><div class="trace-label">${t[1]}</div><div class="trace-title">${t[2]}</div><div class="trace-copy">${t[3]}</div></div>`).join('')}</div></div></div><div style="display:grid;gap:14px">${insights.map(i=>`<div class="card card-p lift"><div style="display:flex;justify-content:space-between;gap:10px;margin-bottom:8px"><div class="card-title">${i.title}</div>${badge(i.type,i.badge)}</div><div class="card-sub" style="font-size:12px;line-height:1.6">${i.body}</div></div>`).join('')}</div></div></div>`; }
function renderReports(){ document.getElementById('s-reports').innerHTML = topbar('Reports','Executive summaries · Steering packs · Exports',[button('Generate pack','ti-file-export','showNarrative()','primary')]) + `<div class="content"><div class="report-page"><div class="report-title">Executive Health Narrative</div><div class="report-body"><p><strong>Portfolio health is amber.</strong> Apex Mobile has an active vendor dependency, Meridian Training has a testing blockage, and Nexus Compliance remains on track.</p><p><strong>Primary driver:</strong> shared external dependency ownership is unclear across two active projects.</p><p><strong>Recommended action:</strong> approve fallback ownership and confirm vendor recovery date before the next steering review.</p><div class="decision-box"><strong>Decision needed:</strong> Approve fallback integration support or accept a 2-week schedule rebaseline.</div></div></div><div class="feature-grid" style="margin-top:14px">${features.filter(f=>f.group==='Reports').map(featureCard).join('')}${featureCard({group:'Reports',icon:'ti-file-spreadsheet',title:'Steering Pack',desc:'RAG, EVM, RAID, CRs, decisions and actions assembled automatically.',tags:['PDF','CSV','Steering']})}${featureCard({group:'Reports',icon:'ti-database-export',title:'Low lock-in exports',desc:'Export module data anytime for backup, audit or migration.',tags:['CSV','JSON','Excel']})}</div></div>`; }
function renderLibrary(){ document.getElementById('s-library').innerHTML = topbar('Templates & Learning Library','Reusable project starters · prior lessons · PM coaching',[button('Use template','ti-template','go(\'setup\')','primary')]) + `<div class="content"><div class="feature-grid">${features.map(featureCard).join('')}</div></div>`; }
function showNarrative(){ showModal('Executive summary','Plain-English health narrative generated from live demo data.', `<div class="report-body"><p><strong>Portfolio health is amber.</strong> Delivery risk increased this sprint because one vendor dependency now affects two project paths.</p><p><strong>Action:</strong> confirm fallback ownership and rebaseline only if vendor recovery is not confirmed by Friday.</p></div>`); }
function showModal(title, sub, body){ document.getElementById('modalTitle').innerHTML=title; document.getElementById('modalSub').innerHTML=sub; document.getElementById('modalBody').innerHTML=body; document.getElementById('modalOverlay').classList.add('open'); }
function hideModal(){ document.getElementById('modalOverlay').classList.remove('open'); }
function closeModal(e){ if(e.target.id==='modalOverlay') hideModal(); }
function openDrawer(project, sprint, status){ const d=document.getElementById('drawer'); d.innerHTML=`<div class="modal-header"><div><div class="modal-title">${project} · ${sprint}</div><div class="modal-sub">Sprint intelligence drawer · status ${status}</div></div><button class="modal-close" onclick="closeDrawer()"><i class="ti ti-x"></i></button></div><div class="modal-body"><div class="narrative-card" style="margin-bottom:14px"><div class="narrative-icon"><i class="ti ti-pulse"></i></div><div><h3>Sprint signal</h3><p>This sprint is ${status}. Vendor milestone risk is the leading indicator. Recommended next step: confirm owner and recovery date.</p></div></div><div class="flow-card">${flowStep(1,'Committed','42 story points')}${flowStep(2,'Completed','27 story points')}${flowStep(3,'Blocked','Vendor API certification')}${flowStep(4,'Learning','Add fallback plan before integration sprint')}</div></div>`; d.classList.add('open'); document.getElementById('drawerOverlay').classList.add('open'); }
function closeDrawer(){ document.getElementById('drawer').classList.remove('open'); document.getElementById('drawerOverlay').classList.remove('open'); }
function boot(){ renderNav(); renderRoleBar(); renderRoleCards(); document.getElementById('continueRole').onclick=()=>enterApp(selectedRole); renderDashboard(); buildWizard(); renderProject(); renderDelivery(); renderGovernance(); renderPeople(); renderIntelligence(); renderReports(); renderLibrary(); }
document.addEventListener('DOMContentLoaded', boot);
