let currentRole='portfolio';
document.addEventListener('DOMContentLoaded',()=>{renderIntentCards();renderNav();renderRoleBar();renderAllSections();runIntro();});
function runIntro(){const lines=['Track delivery.','Trace causes.','Learn patterns.','Understanding your delivery environment…'];const el=document.getElementById('intro-line');let i=0;const t=setInterval(()=>{i++;if(i<lines.length){el.style.opacity=0;setTimeout(()=>{el.textContent=lines[i];el.style.opacity=1},120)}else{clearInterval(t);setTimeout(()=>document.getElementById('intro').classList.remove('open'),450)}},520)}
function selectRole(id){currentRole=id;const role=ROLES.find(r=>r.id===id);document.getElementById('build-copy').textContent='Preparing '+role.role+' workspace.';document.getElementById('build-steps').innerHTML=['Selecting role-aware navigation','Generating starter dashboards','Linking delivery intelligence','Preparing narrative surfaces'].map((s,i)=>`<div class="build-step" id="bs-${i}"><i class="ti ti-circle-dashed"></i>${s}</div>`).join('');document.getElementById('build-screen').classList.add('open');let i=0;const timer=setInterval(()=>{const step=document.getElementById('bs-'+i);if(step){step.classList.add('done');step.innerHTML='<i class="ti ti-check"></i>'+step.textContent}i++;if(i>4){clearInterval(timer);setTimeout(()=>{document.getElementById('intent-screen').classList.add('hidden');document.getElementById('build-screen').classList.remove('open');document.getElementById('app').classList.remove('hidden');switchRole(id);},360)}},420)}
function switchRole(id){currentRole=id;const role=ROLES.find(r=>r.id===id);document.querySelectorAll('.role-btn').forEach(b=>b.classList.toggle('active',b.textContent===role.role));document.querySelector('#role-chip strong').textContent=role.role+' workspace';if(id==='sponsor')go('executive');else if(id==='newpm')go('guided-setup');else if(id==='team')go('sprint');else if(id==='programme')go('timeline');else go('dashboard')}
function go(id){document.querySelectorAll('.sec').forEach(s=>s.classList.remove('active'));const sec=document.getElementById('s-'+id);if(sec)sec.classList.add('active');document.querySelectorAll('.sb-item').forEach(a=>a.classList.toggle('active',a.dataset.sec===id));const found=NAV.flatMap(g=>g[1].map(x=>[g[0],...x])).find(x=>x[1]===id);if(found){document.getElementById('section-kicker').textContent=found[0];document.getElementById('section-title').textContent=found[2]}document.getElementById('sidebar').classList.remove('open')}
function resetExperience(){document.getElementById('app').classList.add('hidden');document.getElementById('intent-screen').classList.remove('hidden')}
function toggleSidebar(){document.getElementById('sidebar').classList.toggle('open')}
function openModal(id){document.getElementById(id).classList.add('open')}
function closeModal(id){document.getElementById(id).classList.remove('open')}
function overlayClose(e,id){if(e.target.id===id)closeModal(id)}
function openSprint(project,sprint){document.getElementById('drawer-overlay').classList.add('open');const d=document.getElementById('drawer');d.classList.add('open');d.innerHTML=`<div class="drawer-inner"><button class="btn ghost" onclick="closeDrawer()"><i class="ti ti-arrow-left"></i>Close</button><h2 style="letter-spacing:-.04em">${project}</h2><p style="color:var(--muted)">${sprint} intelligence</p><div class="coach">Sprint risk is amber because a vendor dependency is linked to one blocked card and one pending decision.</div><div class="mini-list" style="margin-top:16px"><span>Recommended action: confirm fallback owner</span><span>Linked risk: R001 Vendor API delay</span><span>Learning candidate: require internal fallback plan before Phase 3</span></div></div>`}
function closeDrawer(){document.getElementById('drawer-overlay').classList.remove('open');document.getElementById('drawer').classList.remove('open')}
function fakeGenerate(){document.getElementById('build-copy').textContent='Generating project structure.';document.getElementById('build-screen').classList.add('open');document.getElementById('build-steps').innerHTML=['Creating project phases','Adding starter risks','Mapping stakeholders','Preparing governance cadence'].map((s,i)=>`<div class="build-step" id="fg-${i}"><i class="ti ti-circle-dashed"></i>${s}</div>`).join('');let i=0;const timer=setInterval(()=>{const step=document.getElementById('fg-'+i);if(step){step.classList.add('done');step.innerHTML='<i class="ti ti-check"></i>'+step.textContent}i++;if(i>4){clearInterval(timer);setTimeout(()=>{document.getElementById('build-screen').classList.remove('open');go('dashboard')},400)}},380)}
