import type { IntentRole } from "@/lib/types";
export const intentRoles:IntentRole[]=[
{id:"newpm",role:"New PM",title:"I need help structuring and running a project",description:"Generate phases, risks, stakeholders, governance and a starter delivery rhythm automatically.",preview:"RAID · Timeline · Stakeholders"},
{id:"pm",role:"Project Manager",title:"I need visibility into delivery risk and execution",description:"Focus on RAID, blockers, sprint health, RAG and active mitigation actions.",preview:"Risks · Issues · Sprint · RAG"},
{id:"programme",role:"Programme Manager",title:"I need to coordinate dependencies across teams",description:"See cross-team dependencies, milestones, sprint drift and escalation paths in one place.",preview:"Timeline · Dependencies · EVM"},
{id:"portfolio",role:"Portfolio Lead",title:"I need portfolio-level intelligence and trends",description:"Prioritise portfolio health, systemic risk, patterns and cross-project learning.",preview:"Health · Patterns · Learning"},
{id:"sponsor",role:"Sponsor",title:"I need concise delivery insights and decisions",description:"Read executive-grade narratives, decisions required, escalations and commercial impact.",preview:"Narratives · Decisions · Steering"},
{id:"team",role:"Team Member",title:"I need visibility into sprint work and blockers",description:"See current sprint work, ownership, blockers and dependencies without PMO noise.",preview:"Sprint · Blockers · Capacity"}];
export const appNav=[["Home","/dashboard","Dashboard"],["Start","/projects/new","Guided Setup"],["Delivery","/raid","RAID"],["Intelligence","/impact-trace","Impact Trace"],["Platform","/integrations","Integrations"]];
export const demoProjects=[["Apex Mobile Platform","Amber","Vendor API milestone slipped; fallback plan active.","amber"],["Nexus Compliance","Green","Controls mapping completed ahead of steering review.","green"],["Meridian Training","Red","Capacity gap causing rollout delay; sponsor decision needed.","red"],["Orion Data Migration","Green","Cutover rehearsal passed with minor defects.","green"]];
export const connectors=["Microsoft Project","Jira","Azure DevOps","Smartsheet","Excel","ServiceNow","Power BI","Asana"];
